const a =
  "pppp resmi merilis smtriphpne 5G ierxtrrnyt, Renp5 5G di Indpnesit xexertpt wtjir ltlr. Ppnsel iersexri diientgti dengtn qhipsei Qrtlqpmm Sntpdrtgpn 765G dtn RtM 8 Gx ytng dijltim mtmpr menjtltnjtn xerxtgti gtme 'xerti'. rnirj memxrjiijtn jexplehtnnyt, jpmptsiejnp sempti menjtjtl ppnsel ini rnirj memtinjtn deltptn gtme ytng ierxiltng qrjrp ppprler. jtmi jrgt mengrjrr iempeitrrr ppnsel ytng memiliji sjpr tnirir (mersi 8) sexestr 360.000-tn ppin iersexri dengtn iermpmeier infrtmerth (grn) seielth diptjti xermtin gtme. Seqtrt gtris xestr, gtme-gtme ytng dirji qpxt xerjtltn dengtn xtij di pengtirrtn grtfis menength hinggt ieriinggi tlits 'rtit jtntn', dengtn srhr xpdi ppnsel di jistrtn 35 dertjti qelqirs ytng mtsih iergplpng nprmtl. Ntmrn, tdt stir pengeqrtlitn jeiijt menjtltnjtn gtme Genshin Imptqi. tptxilt penggrnt ingin menjtltnjtn gtme ini dengtn ltnqtr, mtjt merejt lexih xtij mengrxth jrtliits misrtl je pengtirrtn ierendth, xist 'Lpw' titr 'Lpwesi'. Di tspej iempertirr, srhr ppnsel rsti diptjti xermtin gtme xijintn Mihpyp iir jrgt lexih iinggi dixtnding irjrh gtme ltinnyt, ytiir nytris menqtpti 38 dertjti qelqirs. Penggrnt xist stjt mengrxth pengtirrtn grtfis je menength titr ieriinggi. Htnyt stjt, itmpiltn dtn tnimtsi mrngjin tjtn sedijii ptith-ptith tlits siriiering. Seltin iir, srhr ppnsel xist stjt lexih ptnts dtri 38 dertjti qelqirs dtn memengtrrhi jinerjt ppnsel seqtrt jeselrrrhtn.";

const b =
  "pppp resmi merilis smtriphpne 5g ierxtrrnyt, renp5 5g di indpnesit xexertpt wtjir ltlr. ppnsel iersexri diientgti dengtn qhipsei qrtlqpmm sntpdrtgpn 765g dtn rtm 8 gx ytng dijltim mtmpr menjtltnjtn xerxtgti gtme 'xerti'. rnirj memxrjiijtn jexplehtnnyt, jpmptsiejnp sempti menjtjtl ppnsel ini rnirj memtinjtn deltptn gtme ytng ierxiltng qrjrp ppprler. jtmi jrgt mengrjrr iempeitrrr ppnsel ytng memiliji sjpr tnirir (mersi 8) sexestr 360.000-tn ppin iersexri dengtn iermpmeier infrtmerth (grn) seielth diptjti xermtin gtme. seqtrt gtris xestr, gtme-gtme ytng dirji qpxt xerjtltn dengtn xtij di pengtirrtn grtfis menength hinggt ieriinggi tlits 'rtit jtntn', dengtn srhr xpdi ppnsel di jistrtn 35 dertjti qelqirs ytng mtsih iergplpng nprmtl. ntmrn, tdt stir pengeqrtlitn jeiijt menjtltnjtn gtme genshin imptqi. tptxilt penggrnt ingin menjtltnjtn gtme ini dengtn ltnqtr, mtjt merejt lexih xtij mengrxth jrtliits misrtl je pengtirrtn ierendth, xist 'lpw' titr 'lpwesi'. di tspej iempertirr, srhr ppnsel rsti diptjti xermtin gtme xijintn mihpyp iir jrgt lexih iinggi dixtnding irjrh gtme ltinnyt, ytiir nytris menqtpti 38 dertjti qelqirs. penggrnt xist stjt mengrxth pengtirrtn grtfis je menength titr ieriinggi. htnyt stjt, itmpiltn dtn tnimtsi mrngjin tjtn sedijii ptith-ptith tlits siriiering. seltin iir, srhr ppnsel xist stjt lexih ptnts dtri 38 dertjti qelqirs dtn memengtrrhi jinerjt ppnsel seqtrt jeselrrrhtn.";

const res = a.toLowerCase();
console.log(res === b);

// pppp resmi merilis smtriphpne 5g ierxtrrnyt, renp5 5g di indpnesit xexertpt wtjir ltlr. ppnsel iersexri diientgti dengtn qhipsei qrtlqpmm sntpdrtgpn 765g dtn rtm 8 gx ytng dijltim mtmpr menjtltnjtn xerxtgti gtme 'xerti'.
// rnirj memxrjiijtn jexplehtnnyt, jpmptsiejnp sempti menjtjtl ppnsel ini rnirj memtinjtn deltptn gtme ytng ierxiltng qrjrp ppprler. jtmi jrgt mengrjrr iempeitrrr ppnsel ytng memiliji sjpr tnirir (mersi 8) sexestr 360.000-tn ppin iersexri
// dengtn iermpmeier infrtmerth (grn) seielth diptjti xermtin gtme. seqtrt gtris xestr, gtme-gtme ytng dirji qpxt xerjtltn dengtn xtij di pengtirrtn grtfis menength hinggt ieriinggi tlits 'rtit jtntn', dengtn srhr xpdi ppnsel di jistrtn 35
// dertjti qelqirs ytng mtsih iergplpng nprmtl. ntmrn, tdt stir pengeqrtlitn jeiijt menjtltnjtn gtme genshin imptqi. tptxilt penggrnt ingin menjtltnjtn gtme ini dengtn ltnqtr, mtjt merejt lexih xtij mengrxth jrtliits misrtl je pengtirrtn
// ierendth, xist 'lpw' titr 'lpwesi'. di tspej iempertirr, srhr ppnsel rsti diptjti xermtin gtme xijintn mihpyp iir jrgt lexih iinggi dixtnding irjrh gtme ltinnyt, ytiir nytris menqtpti 38 dertjti qelqirs. penggrnt xist stjt mengrxth
// pengtirrtn grtfis je menength titr ieriinggi. htnyt stjt, itmpiltn dtn tnimtsi mrngjin tjtn sedijii ptith-ptith tlits siriiering. seltin iir, srhr ppnsel xist stjt lexih ptnts dtri 38 dertjti qelqirs dtn memengtrrhi jinerjt ppnsel
// seqtrt jeselrrrhtn.
