# make baseImage apa
FROM node:16-alpine

WORKDIR /app

COPY package*.json ./
RUN yarn

COPY ./ ./

CMD ["yarn", "run", "start"]

# untuk bisa jalanain yang dibawah nama Dodckerfile nya harus diganti dnegan tanpa dev

# command untuk ngebuild image dockernya
# docker build -t reactjs/tic-tac-toe:1.0.0 ./
# setelah selesai build, cek images nya dari command "docker images"

# 3000:3000 artinya 3000 kiri untuk port output dan 3000 yang kanan dari port project yang dirunning
# command running container nya "docker run -d -p 3000:3000 reactjs/tic-tac-toe:1.0.0"

# cek status docker containernya yang jalan dengan command "docker ps"

# command mattin docker containernya
# docker container stop nama_container
# docker container stop stupefied_carver 