const a =
  "eerarbnpaangihieaakkkhrntaaxkiteamnxdadinuusxkaduptkhexanapeaaamxgnsrhlruxgemmauaxpaehsuxintmpxaeeaxtnyxgaxtxx";
const res = a.toUpperCase();
// console.log(res);

const c =
  "B D S A B A I D E A D A I A P X X A I T T A R H I E S I N S M E X X L L A A G I N K K K M G I O R X X A I R N U N Y U R A O D S T F X X P H T S S S A T O N T I T O O X X A A S A D A M I S D O A A R R X X N T A Y I Y A P S A G W R N M X X T D Y A B A N D I L P A T Y A X X I A A J A M U A P A P L K A L X X D R D U N E J R U M O I E M E X X A I A G D R A I N B R D I E B X X K P N A I A R S M A T A A M I X X B O K L N S R P E L U R M I H X X U S E E G A O E N A G I E L B X X R I C B K L S E J P A P R I A X X U S E I E E S D E A L O A K I X X K I P H M B I W L N Y S S I K X X";

const d =
  "BDSABAIDEADAIAPXX-AITTARHIESINSMEXX-LLAAGINKKKMGIORXX-AIRNUNYURAODSTFXX-PHTSSSATONTITOOXX-AASADAMISDOAARRXX-NTAYIYAPSAGWRNMXX-TDYABANDILPATYAXX-IAAJAMUAPAPLKALXX-DRDUNEJRUMOIEMEXX-AIAGDRAINBRDIEBXX-KPNAIARSMATAAMIXX-BOKLNSRPELURMIHXX-USEEGAOENAGIELBXX-RICBKLSEJPAPRIAXX-USEIEESDEALOAKIXX-KIPHMBIWLNYSSIKXX";

let cResult = "";
for (let i = 0; i < c.length; i++) {
  if (c[i] === " ") {
    continue;
  } else {
    cResult += c[i];
  }
}

// console.log(cResult);

// BDSABAIDEADAIAPXXAITTARHIESINSMEXXLLAAGINKKKMGIORXXAIRNUNYURAODSTFXXPHTSSSATONTITOOXXAASADAMISDOAARRXXNTAYIYAPSAGWRNMXXTDYABANDILPATYAXXIAAJAMUAPAPLKALXXDRDUNEJRUMOIEMEXXAIAGDRAINBRDIEBXXKPNAIARSMATAAMIXXBOKLNSRPELURMIHXXUSEEGAOENAGIELBXXRICBKLSEJPAPRIAXXUSEIEESDEALOAKIXXKIPHMBIWLNYSSIKXX

let dResult = "";
for (let i = 0; i < d.length; i++) {
  if (d[i] === "-") {
    continue;
  } else {
    dResult += d[i];
  }
}

// console.log(dResult);

// BDSABAIDEADAIAPXXAITTARHIESINSMEXXLLAAGINKKKMGIORXXAIRNUNYURAODSTFXXPHTSSSATONTITOOXXAASADAMISDOAARRXXNTAYIYAPSAGWRNMXXTDYABANDILPATYAXXIAAJAMUAPAPLKALXXDRDUNEJRUMOIEMEXXAIAGDRAINBRDIEBXXKPNAIARSMATAAMIXXBOKLNSRPELURMIHXXUSEEGAOENAGIELBXXRICBKLSEJPAPRIAXXUSEIEESDEALOAKIXXKIPHMBIWLNYSSIKXX

console.log(cResult === dResult);
